# Generated by Django 5.1.1 on 2024-09-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_deadline_alter_todo_fineshed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["deadline"]},
        ),
        migrations.RenameField(
            model_name="todo",
            old_name="fineshed_at",
            new_name="finished_at",
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(blank=True, verbose_name="Data de entrega"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
